sudo: required
dist: trusty

matrix:
    include:
        - python: "3.6"
          language: python
          env: TARGET=linux
          dist: xenial
          sudo: required
        - python: "3.7"
          language: python
          env: TARGET=linux
          dist: xenial
          sudo: required

addons:
    apt:
        packages:
            - libboost-python-dev
            - libgraphicsmagick++1-dev
            - python3-setuptools
            - gsfonts

before_install:
    - ls /usr/bin
    - ls /home/travis

install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6"* ]]; then python setup.py install; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.7"* ]]; then python setup.py install; fi

script:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6"* ]]; then make test; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.7"* ]]; then make test; fi
