dist: trusty

matrix:
    include:
        - python: "3.6"
          language: python
          env: TARGET=linux
          dist: xenial
          before_install:
              - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu disco main"
              - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu disco universe"
              - sudo add-apt-repository -y ppa:deadsnakes/ppa
              - sudo apt-get update
              - sudo apt-get install -y python3.6 python3.6-dev libboost-python-dev libgraphicsmagick++1-dev python3-setuptools gsfonts

install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6"* ]]; then sudo mkdir -p /usr/lib/python3.6/site-packages/; sudo /usr/bin/python3.6 setup.py install; fi

script:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6"* ]]; then PYTHON=/usr/bin/python3.6 make test; fi
