dist: trusty

matrix:
    include:
        - python: "3.5"
          language: python
          env: TARGET=linux
          dist: xenial      # use python3.5
          sudo: required
        - python: "3.6"
          language: python
          env: TARGET=linux
          dist: xenial
          sudo: required
          before_install:
              - sudo add-apt-repository -y ppa:deadsnakes/ppa
              - sudo apt-get update
              - sudo apt-get install -y python3.6 python3-dev
              - ls /usr/bin
        - python: "3.7"
          language: python
          env: TARGET=linux
          dist: xenial
          sudo: required

addons:
    apt:
        packages:
            - libboost-python-dev
            - libgraphicsmagick++1-dev
            - python3-setuptools
            - gsfonts

install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.5"* ]]; then python setup.py install; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6"* ]]; then sudo mkdir -p /usr/lib/python3.6/site-packages/; sudo /usr/bin/python3.6 setup.py install; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.7"* ]]; then python setup.py install; fi

script:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.5"* ]]; then make test; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6"* ]]; then PYTHON=/usr/bin/python3.6 make test; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.7"* ]]; then make test; fi
